resources:
  Resources:
    NewsFeedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriNewsFeeds'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    NewsFeedAttachmentQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'news-feed-attachment.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    NewsFeedAttachmentSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt NewsFeedAttachmentQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewNewsFeedAttachmentVersion']