version: '3.9'

services:
  mysql:
    image: mysql:5.7
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'MYSQL_USER=barueri'
      - 'MYSQL_PASSWORD=barueri'
      - 'MYSQL_DATABASE=barueri'
    ports:
      - '3366:3306'
    volumes:
      - '.local/schema.sql:/docker-entrypoint-initdb.d/schema.sql'
  sqs:
    image: softwaremill/elasticmq
    ports:
      - '9324:9324'
      - '9325:9325'
  dynamodb:
    image: amazon/dynamodb-local:1.18.0
    ports:
      - '8080:8000'
    # motivo do comando abaixo:
    # https://github.com/99x/serverless-dynamodb-local/issues/57#issuecomment-609093479
    # https://github.com/99x/serverless-dynamodb-local/issues/57#issuecomment-609098256
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
