resources:
  Resources:
    TrainingProgressesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriTrainingProgresses'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: _employee_training
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: _employee_training
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    TrainingProgressMysqlQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'training-progress-mysql.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    TrainingProgressMysqlSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt TrainingProgressMysqlQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewTrainingProgressVersion']
