resources:
  Resources:
    UsersUpdateHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriUsersUpdateHistory'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: user_created_at
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: user_created_at
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    UserUpdateHistoryQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'user-update-history.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    UserUpdateHistorySub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt UserUpdateHistoryQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewUserVersion']
