resources:
  Resources:
    TemplatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriTemplates'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: type
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

        GlobalSecondaryIndexes:
          -
            IndexName: 'BarueriTemplatesByAccountAndType'
            KeySchema:
              -
                AttributeName: account
                KeyType: HASH
              -
                AttributeName: type
                KeyType: RANGE
            Projection:
              ProjectionType: ALL