import {EvaluationType} from './schema';

const EmotionalInteligenceEvalutionSchema = {
    lang: 'pt-BR',
    type: 'multidirectional.ie',
    title: 'Inteligência Emocional',
    positive: true,
    schema: {type: 'integer', minimum: 1, maximum: 5},
    abilitySchema: {type: 'integer', minimum: 1, maximum: 5},
    regions: {bad: [1, 2.5], median: [2.5, 4.5], good: [4.5, 5]},
    competencies: [
        {id: 'personal', title: 'Pessoais', text: 'Competências emocionais pessoais'},
        {id: 'social', title: 'Sociais', text: 'Competências emocionais sociais'},
    ],
    abilities: [
        {id: '1', competency: 'personal', title: 'Autoconsciência emocional'},
        {id: '2', competency: 'personal', title: 'Autoavaliação precisa'},
        {id: '3', competency: 'personal', title: 'Autoconfiança'},
        {id: '4', competency: 'personal', title: 'Autocontrole emocional'},
        {id: '5', competency: 'personal', title: 'Superação'},
        {id: '6', competency: 'personal', title: 'Iniciativa'},
        {id: '7', competency: 'personal', title: 'Transparência'},
        {id: '8', competency: 'personal', title: 'Adaptabilidade'},
        {id: '9', competency: 'personal', title: 'Otimismo'},
        {id: '10', competency: 'social', title: 'Empatia'},
        {id: '11', competency: 'social', title: 'Consciência organizacional'},
        {id: '12', competency: 'social', title: 'Serviço'},
        {id: '13', competency: 'social', title: 'Liderança inspiradora'},
        {id: '14', competency: 'social', title: 'Influência'},
        {id: '15', competency: 'social', title: 'Desenvolvimento dos demais'},
        {id: '16', competency: 'social', title: 'Catalisação de mudanças'},
        {id: '17', competency: 'social', title: 'Gerenciamento de conflitos'},
        {id: '18', competency: 'social', title: 'Trabalho em equipe'},
    ],
    questions: [
        {id: '1', ability: '1', text: 'Identificar suas próprias emoções e reconhecer seu impacto nas ações e decisões'},
        {id: '2', ability: '2', text: 'Conhecer seus próprios limites e possibilidades, sem se supervalorizar ou subestimar'},
        {id: '3', ability: '3', text: 'Possuir um sólido senso do seu próprio valor, capacidade e potência'},
        {id: '4', ability: '4', text: 'Manter emoções e impulsos destrutivos sob controle'},
        {id: '5', ability: '5', text: 'Demonstrar ímpeto para melhorar o desempenho a fim de satisfazer padrões interiores de excelência'},
        {id: '6', ability: '6', text: 'Estar sempre de prontidão para agir e aproveitar oportunidades'},
        {id: '7', ability: '7', text: 'Ser honesto, íntegro, digno de confiança'},
        {id: '8', ability: '8', text: 'Flexibilidade na adaptação a pessoas com estilos diferentes e a situações voláteis ou ao pensar e se comportar em situações antagônicas'},
        {id: '9', ability: '9', text: 'Ver o lado bom dos acontecimentos em qualquer situação que seja'},
        {id: '10', ability: '10', text: 'Perceber as emoções alheias, compreender seus pontos de vista e interessar-se ativamente por suas preocupações'},
        {id: '11', ability: '11', text: 'Identificar e compreender as tendências, redes de decisão e a política em nível organizacional'},
        {id: '12', ability: '12', text: 'Reconhecer e satisfazer às necessidades dos subordinados e clientes, servindo-os e ajudando-os a melhorarem seu desempenho e alcançarem seus objetivos'},
        {id: '13', ability: '13', text: 'Orientar e motivar com uma visão instigante, conduzindo pessoas a objetivos de ganhos mútuos'},
        {id: '14', ability: '14', text: 'Dispor de capacidade de persuadir e influenciar pessoas'},
        {id: '15', ability: '15', text: 'Cultivar as capacidades alheias por meio de feedbacks e orientação'},
        {id: '16', ability: '16', text: 'Iniciar e gerenciar mudanças e liderar pessoas em uma nova direção'},
        {id: '17', ability: '17', text: 'Solucionar divergências entre pessoas levando-as à integração e à aceitação mútua'},
        {id: '18', ability: '18', text: 'Conquistar a colaboração e o trabalho em equipe com alto desempenho'},
    ],
};

const PrideEvalutionSchema = {
    lang: 'pt-BR',
    type: 'multidirectional.o',
    title: 'Orgulho',
    positive: false,
    schema: {type: 'integer', minimum: 1, maximum: 5},
    abilitySchema: {type: 'integer', minimum: 1, maximum: 5},
    regions: {good: [1, 2.5], median: [2.5, 4.5], bad: [4.5, 5]},
    competencies: [
        {id: 'pride', title: 'Orgulho', text: 'Manifestações do Orgulho'},
    ],
    abilities: [
        {id: '1', competency: 'pride', title: 'Arrogância'},
        {id: '2', competency: 'pride', title: 'Prepotência'},
        {id: '3', competency: 'pride', title: 'Vaidade'},
        {id: '4', competency: 'pride', title: 'Falta de Perdão'},
        {id: '5', competency: 'pride', title: 'Mentira'},
        {id: '6', competency: 'pride', title: 'Zona de Conforto'},
        {id: '7', competency: 'pride', title: 'Autossuficiência'},
        {id: '8', competency: 'pride', title: 'Ingenuidade'},
        {id: '9', competency: 'pride', title: 'Desobediência'},
        {id: '10', competency: 'pride', title: 'Insatisfação'},
        {id: '11', competency: 'pride', title: 'Desonra-Desrespeito'},
        {id: '12', competency: 'pride', title: 'Inveja'},
        {id: '13', competency: 'pride', title: 'Impaciência'},
    ],
    questions: [
        {id: '1', ability: '1', text: 'enaltecer a si mesmo'},
        {id: '2', ability: '2', text: 'achar que pode sem mesmo ainda poder'},
        {id: '3', ability: '3', text: 'viver baseado na aparência e estética'},
        {id: '4', ability: '4', text: 'se achar tão superior ao ponto de não precisar perdoar o outro'},
        {id: '5', ability: '5', text: 'grito desesperado de convencer que é melhor do que imagina'},
        {id: '6', ability: '6', text: 'acreditar que sem fazer o necessário prosperará'},
        {id: '7', ability: '7', text: 'acreditar ou dizer que não precisa de ajuda'},
        {id: '8', ability: '8', text: 'achar que crescerá sem as ferramentas/conhecimentos necessários'},
        {id: '9', ability: '9', text: 'falta intencional de subordinação'},
        {id: '10', ability: '10', text: 'vício emocional de reclamar ou criticar'},
        {id: '11', ability: '11', text: 'tratar o próximo sem a importância devida'},
        {id: '12', ability: '12', text: 'sentimento tóxico pelo que o outro é, faz ou tem'},
        {id: '13', ability: '13', text: 'forma grosseira de reagir de pessoas que se sentem incomodadas'},
    ],
};

const ManagingSkillsEvalutionSchema = {
    lang: 'pt-BR',
    type: 'multidirectional.hg',
    title: 'Habilidades Gerenciais',
    positive: true,
    schema: {type: 'integer', minimum: 1, maximum: 5},
    abilitySchema: {type: 'integer', minimum: 2, maximum: 10},
    regions: {bad: [2, 5.5], median: [5.5, 8.5], good: [8.5, 10]},
    competencies: [
        {id: 'leadership', title: 'Liderança', text: 'Liderança'},
        {id: 'implementation', title: 'Implementação', text: 'Implementação'},
        {id: 'development', title: 'Desenvolvimento', text: 'Desenvolvimento'},
        {id: 'change-management', title: 'Gerência da Mudança', text: 'Gerência da Mudança'},
    ],
    abilities: [
        {id: '1', competency: 'leadership', title: 'Comunicar a visão'},
        {id: '2', competency: 'leadership', title: 'Esclarecer as expectativas'},
        {id: '3', competency: 'leadership', title: 'Inspirar e motivar'},
        {id: '4', competency: 'leadership', title: 'Ser um bom exemplo'},
        {id: '5', competency: 'leadership', title: 'Representar a equipe'},
        {id: '6', competency: 'implementation', title: 'Planejar e organizar'},
        {id: '7', competency: 'implementation', title: 'Consultar quanto a decisões'},
        {id: '8', competency: 'implementation', title: 'Solucionar problemas'},
        {id: '9', competency: 'implementation', title: 'Agir com justiça'},
        {id: '10', competency: 'implementation', title: 'Concentrar-se nos resultados'},
        {id: '11', competency: 'development', title: 'Orientar e treinar'},
        {id: '12', competency: 'development', title: 'Delegar trabalho'},
        {id: '13', competency: 'development', title: 'Dar feedback'},
        {id: '14', competency: 'development', title: 'Planejar carreira'},
        {id: '15', competency: 'development', title: 'Fomentar a colaboração'},
        {id: '16', competency: 'change-management', title: 'Buscar oportunidade de melhoria'},
        {id: '17', competency: 'change-management', title: 'Assumir riscos'},
        {id: '18', competency: 'change-management', title: 'Informar aos outros'},
        {id: '19', competency: 'change-management', title: 'Reagir bem ao Feedback'},
        {id: '20', competency: 'change-management', title: 'Obter compromisso com a mudança'},
    ],
    questions: [
        {id: '1', ability: '1', text: 'Explica claramente aos subordinados a visão da organização'},
        {id: '2', ability: '1', text: 'Traduz a visão em metas e prioridades para o pessoal na sua área'},
        {id: '3', ability: '2', text: 'Explica quais são os comportamentos e resultados que espera da equipe'},
        {id: '4', ability: '2', text: 'Estabelece e comunica padrões específicos de desempenho individual'},
        {id: '5', ability: '3', text: 'Gera entusiasmo e compromisso com o atingimento de metas comuns'},
        {id: '6', ability: '3', text: 'Dedica tempo a motivar individualmente os membros da equipe'},
        {id: '7', ability: '4', text: 'Comporta-se de maneira consistente com a visão, as metas e as prioridades da organização'},
        {id: '8', ability: '4', text: 'Assume responsabilidade pessoal pelo seu desempenho'},
        {id: '9', ability: '5', text: 'Demonstra apoio à equipe, comunicando as opiniões e as decisões desta para pessoas de fora'},
        {id: '10', ability: '5', text: 'Fala bem da equipe ao lidar com pessoas de fora (por exemplo, clientes de outras organizações)'},
        {id: '11', ability: '6', text: 'Comunica e desenvolve planos bem elaborados para o futuro'},
        {id: '12', ability: '6', text: 'Proporciona recursos, sistemas e procedimentos adequados para implementação dos planos'},
        {id: '13', ability: '7', text: 'Procura contar com a opinião dos outros ao tomar decisões importantes'},
        {id: '14', ability: '7', text: 'Mostra respeito pelas opiniões dos membros da equipe'},
        {id: '15', ability: '8', text: 'Ao solucionar problemas, assegura que os mesmos tenham sido corretamente identificados e compreendidos'},
        {id: '16', ability: '8', text: 'Consegue gerar boa variedade de soluções, avaliar os prováveis resultados e agir com confiança'},
        {id: '17', ability: '9', text: 'Aplica as mesmas normas e regras para si mesmo e para todos os membros da equipe'},
        {id: '18', ability: '9', text: 'Consegue reconhecer princípios que foram injustamente aplicados e fazer as devidas correções'},
        {id: '19', ability: '10', text: 'Desenvolve sistemas de medida claros e práticos, que ajudam os outros a melhorar o desempenho e os resultados globais'},
        {id: '20', ability: '10', text: 'Propicia oportunidades para rever o progresso da equipe e acompanhar resultados'},
        {id: '21', ability: '11', text: 'Assegura que as necessidades de treinamento e desenvolvimento individuais e da equipe sejam corretamente avaliadas'},
        {id: '22', ability: '11', text: 'Desenvolve métodos eficazes para propiciar o desenvolvimento'},
        {id: '23', ability: '12', text: 'Consegue designar pessoas certas para os trabalhos certos, nas horas certas'},
        {id: '24', ability: '12', text: 'Ao delegar trabalho, confia dando orientações claras'},
        {id: '25', ability: '13', text: 'Dá feedback positivo regularmente às pessoas e à equipe pelas suas realizações'},
        {id: '26', ability: '13', text: 'Consegue dar feedbacks construtivos para obter melhorias no desempenho'},
        {id: '27', ability: '14', text: 'Ajuda os membros da equipe a avaliarem de modo realista suas opções para desenvolvimento e oportunidades para mudança e melhoria'},
        {id: '28', ability: '14', text: 'Promove os valores de iguais oportunidades em todos os níveis'},
        {id: '29', ability: '15', text: 'Participa das atividades que fortalecem os relacionamentos na equipe'},
        {id: '30', ability: '15', text: 'Cria relacionamentos construtivos com gente de fora da equipe (por exemplo - fornecedores, clientes e etc.)'},
        {id: '31', ability: '16', text: 'Procura ativamente maneiras de melhorar o negócio'},
        {id: '32', ability: '16', text: 'Incentiva os outros a pensarem criativamente e usarem de iniciativa para melhorar'},
        {id: '33', ability: '17', text: 'Fica disposto a encontrar novas maneiras de fazer as coisas'},
        {id: '34', ability: '17', text: 'Ao tentar coisas novas, consegue aprender com os erros e se adaptar de maneira positiva'},
        {id: '35', ability: '18', text: 'Comunica-se regularmente com a equipe sobre mudanças'},
        {id: '36', ability: '18', text: 'Ao dar informações sobre mudanças, demonstra sensibilidade ao impacto delas nos membros da equipe'},
        {id: '37', ability: '19', text: 'Busca ativamente ideias da equipe sobre o processo de mudança'},
        {id: '38', ability: '19', text: 'Consegue dar atenção às preocupações da equipe em relação às mudanças'},
        {id: '39', ability: '20', text: 'Consegue efetivamente identificar os motivos da resistência a mudanças'},
        {id: '40', ability: '20', text: 'Identifica maneiras de superar a resistência e conquistar um compromisso com as mudanças'},
    ],
};

const SellDevelopmentEvalutionSchema = {
    lang: 'pt-BR',
    type: 'multidirectional.dv',
    title: 'Desenvolvimento em Vendas',
    positive: true,
    schema: {type: 'integer', minimum: 1, maximum: 5},
    abilitySchema: {type: 'integer', minimum: 2, maximum: 10},
    regions: {bad: [2, 5.5], median: [5.5, 8.5], good: [8.5, 10]},
    competencies: [
        {id: 'update', title: 'Atualização com o Ramo', text: 'Atualização com o Ramo'},
        {id: 'implementation', title: 'Habilidades de Realização', text: 'Habilidades de Realização'},
        {id: 'interpersonal', title: 'Habilidades Interpessoais', text: 'Habilidades Interpessoais'},
        {id: 'selling', title: 'Habilidades em Vendas', text: 'Habilidades em Vendas'},
    ],
    abilities: [
        {id: '1', competency: 'update', title: 'Compreender o mercado'},
        {id: '2', competency: 'update', title: 'Compreender a empresa'},
        {id: '3', competency: 'update', title: 'Conhecer os produtos/serviços'},
        {id: '4', competency: 'implementation', title: 'Ter motivação para o sucesso'},
        {id: '5', competency: 'implementation', title: 'Manter alto nível de vitalidade'},
        {id: '6', competency: 'implementation', title: 'Administrar bem o tempo'},
        {id: '7', competency: 'implementation', title: 'Concentrar-se em atender o cliente'},
        {id: '8', competency: 'implementation', title: 'Administrar com eficiência'},
        {id: '9', competency: 'interpersonal', title: 'Causar impressão positiva'},
        {id: '10', competency: 'interpersonal', title: 'Criar relacionamentos'},
        {id: '11', competency: 'interpersonal', title: 'Fazer perguntas eficazes'},
        {id: '12', competency: 'interpersonal', title: 'Escutar com atenção'},
        {id: '13', competency: 'interpersonal', title: 'Reagir adequadamente'},
        {id: '14', competency: 'selling', title: 'Gerar novos negócios'},
        {id: '15', competency: 'selling', title: 'Apresentar produtos'},
        {id: '16', competency: 'selling', title: 'Atender as necessidades de venda adicional'},
        {id: '17', competency: 'selling', title: 'Criar oportunidades de venda adicional'},
        {id: '18', competency: 'selling', title: 'Superar objeções'},
        {id: '19', competency: 'selling', title: 'Fechar vendas'},
        {id: '20', competency: 'selling', title: 'Maximizar pedidos repetidos'},
    ],
    questions: [
        {id: '1', ability: '1', text: 'Conhece as características e as necessidades do mercado'},
        {id: '2', ability: '1', text: 'É proativo em se manter atualizado em relação ao seu ramo de atividade'},
        {id: '3', ability: '2', text: 'Utiliza os sistemas e os procedimentos da organização de modo competente'},
        {id: '4', ability: '2', text: 'Conhece os pontos fortes das principais pessoas na organização'},
        {id: '5', ability: '3', text: 'Saber descrever com clareza a linha de produtos e/ou serviços da empresa'},
        {id: '6', ability: '3', text: 'Consegue explicar as características e os benefícios de cada produto ou serviço'},
        {id: '7', ability: '4', text: 'Empenha-se em atingir metas desafiantes'},
        {id: '8', ability: '4', text: 'Procura constantemente maneiras de melhorar o próprio desempenho'},
        {id: '9', ability: '5', text: 'Preserva a autoconfiança, mesmo depois de rejeições consecutivas'},
        {id: '10', ability: '5', text: 'Mantém a persistência ao longo do tempo'},
        {id: '11', ability: '6', text: 'É pontual em reuniões e outros compromissos'},
        {id: '12', ability: '6', text: 'Prioriza as tarefas de maneira eficaz, evitando a perda de tempo'},
        {id: '13', ability: '7', text: 'Mostra disposição para ajudar os outros'},
        {id: '14', ability: '7', text: 'Consistentemente oferece aos clientes mais que o esperado'},
        {id: '15', ability: '8', text: 'Sempre presta muita atenção em detalhes'},
        {id: '16', ability: '8', text: 'Executa eficientemente todas as tarefas administrativas'},
        {id: '17', ability: '9', text: 'Obtém entrosamento através de saudações e usando o nome do cliente'},
        {id: '18', ability: '9', text: 'Cria uma primeira impressão de profissionalismo, pela aparência e modo de falar'},
        {id: '19', ability: '10', text: 'Mostra respeito pelas necessidades individuais e preocupações do cliente'},
        {id: '20', ability: '10', text: 'Comunica-se com facilidade com uma grande variedade de clientes'},
        {id: '21', ability: '11', text: 'Faz perguntas relevantes para determinar as necessidades do cliente'},
        {id: '22', ability: '11', text: 'Consegue obter informações úteis dos clientes'},
        {id: '23', ability: '12', text: 'Escuta com atenção e faz um resumo para verificar se entendeu'},
        {id: '24', ability: '12', text: 'Não interrompe as pessoas durante a conversa'},
        {id: '25', ability: '13', text: 'Responde prontamente a perguntas e preocupações'},
        {id: '26', ability: '13', text: 'Cumpre suas promessas e compromissos'},
        {id: '27', ability: '14', text: 'Encontra oportunidades para promover o negócio'},
        {id: '28', ability: '14', text: 'É criativo na busca de clientes em potencial'},
        {id: '29', ability: '15', text: 'Motiva e inspira as pessoas quando apresenta produtos e/ ou serviços'},
        {id: '30', ability: '15', text: 'Destaca os argumentos exclusivos do negócio que oferece, mas sem exagerar'},
        {id: '31', ability: '16', text: 'Oferece produtos/serviços adequados às necessidades específicas do cliente'},
        {id: '32', ability: '16', text: 'Consegue fazer a ligação entre os benefícios e as necessidades do cliente'},
        {id: '33', ability: '17', text: 'Mostra firmeza ao propor uma venda maior'},
        {id: '34', ability: '17', text: 'Encontra oportunidade para vender adicionais a clientes existentes'},
        {id: '35', ability: '18', text: 'Antevê e supera as objeções antes que sejam levantadas'},
        {id: '36', ability: '18', text: 'Utiliza diversas técnicas para transformar objeções em oportunidades'},
        {id: '37', ability: '19', text: 'Consistentemente transforma um simples interesse em vendas'},
        {id: '38', ability: '19', text: 'Negocia com eficácia quando necessário'},
        {id: '39', ability: '20', text: 'Mantém contato com o cliente após a venda'},
        {id: '40', ability: '20', text: 'Gera grande lealdade dos clientes'},
    ],
};

const WorkEfficacyEvalutionSchema = {
    lang: 'pt-BR',
    type: 'multidirectional.et',
    title: 'Eficácia no Trabalho',
    positive: true,
    schema: {type: 'integer', minimum: 1, maximum: 5},
    abilitySchema: {type: 'integer', minimum: 2, maximum: 10},
    regions: {bad: [2, 5.5], median: [5.5, 8.5], good: [8.5, 10]},
    competencies: [
        {id: 'productivity', title: 'Produtividade', text: 'Produtividade'},
        {id: 'team-working', title: 'Trabalho em Equipe', text: 'Trabalho em Equipe'},
        {id: 'future-acceptance', title: 'Receptividade ao Futuro', text: 'Receptividade ao Futuro'},
        {id: 'pressure-work', title: 'Capacidade de Trabalhar sob Pressão', text: 'Capacidade de Trabalhar sob Pressão'},
    ],
    abilities: [
        {id: '1', competency: 'productivity', title: 'Concentrar-se nos resultados'},
        {id: '2', competency: 'productivity', title: 'Manter a qualidade'},
        {id: '3', competency: 'productivity', title: 'Tomar iniciativa'},
        {id: '4', competency: 'team-working', title: 'Buscar melhorias'},
        {id: '5', competency: 'team-working', title: 'Organizar-se bem'},
        {id: '6', competency: 'team-working', title: 'Comunicar informações'},
        {id: '7', competency: 'team-working', title: 'Cumprir as promessas'},
        {id: '8', competency: 'team-working', title: 'Ser franco e sincero'},
        {id: '9', competency: 'future-acceptance', title: 'Resolver conflitos produtivamente'},
        {id: '10', competency: 'future-acceptance', title: 'Voltar-se sempre para o cliente'},
        {id: '11', competency: 'future-acceptance', title: 'Ser positivo diante das mudanças'},
        {id: '12', competency: 'future-acceptance', title: 'Aprender rapidamente'},
        {id: '13', competency: 'future-acceptance', title: 'Conviver bem com a tecnologia'},
        {id: '14', competency: 'pressure-work', title: 'Administrar a própria carreira'},
        {id: '15', competency: 'pressure-work', title: 'Pensar à frente'},
        {id: '16', competency: 'pressure-work', title: 'Tolerar bem a incerteza'},
        {id: '17', competency: 'pressure-work', title: 'Fazer mais com menos'},
        {id: '18', competency: 'pressure-work', title: 'Ser muito flexível'},
        {id: '19', competency: 'pressure-work', title: 'Ter estabilidade emocional'},
        {id: '20', competency: 'pressure-work', title: 'Buscar inovação'},
    ],
    questions: [
        {id: '1', ability: '1', text: 'Tem um compromisso assumido com as metas da organização'},
        {id: '2', ability: '1', text: 'Atinge os resultados desejados'},
        {id: '3', ability: '2', text: 'Presta muita atenção em detalhes'},
        {id: '4', ability: '2', text: 'Procura trabalhar consistentemente num alto nível'},
        {id: '5', ability: '3', text: 'Resolve problemas rapidamente'},
        {id: '6', ability: '3', text: 'Toma decisões apropriadas quando necessário'},
        {id: '7', ability: '4', text: 'Contribui com ideias e sugestões para melhoria'},
        {id: '8', ability: '4', text: 'É receptivo às ideias dos outros para melhorar'},
        {id: '9', ability: '5', text: 'Consegue administrar as grandes prioridades'},
        {id: '10', ability: '5', text: 'Tem práticas e sistemas eficientes para o seu trabalho individual'},
        {id: '11', ability: '6', text: 'Transmite as informações relevantes aos outros de maneira eficiente'},
        {id: '12', ability: '6', text: 'Consegue destacar os pontos principais ao se comunicar'},
        {id: '13', ability: '7', text: 'Acompanha todos os seus compromissos'},
        {id: '14', ability: '7', text: 'Informa os outros quando não terá condições de cumprir uma promessa'},
        {id: '15', ability: '8', text: 'Fica à vontade ao expressar suas opiniões'},
        {id: '16', ability: '8', text: 'É habilidoso ao dar e receber feedback sobre desempenho'},
        {id: '17', ability: '9', text: 'Consegue lidar com situações de conflito de maneira colaborativa'},
        {id: '18', ability: '9', text: 'Ajuda a mediar conflitos entre outras pessoas'},
        {id: '19', ability: '10', text: 'Mostra disposição para ajudar clientes internos e externos'},
        {id: '20', ability: '10', text: 'Procura exceder as expectativas dos clientes sempre que possível'},
        {id: '21', ability: '11', text: 'É receptivo a qualquer mudança que leve a um desempenho melhor'},
        {id: '22', ability: '11', text: 'Mantém-se disposto a trabalhar pela implementação de mudanças'},
        {id: '23', ability: '12', text: 'Age de maneira proativa ao buscar oportunidades para aprender'},
        {id: '24', ability: '12', text: 'Adapta-se com facilidade a novos sistemas e processos'},
        {id: '25', ability: '13', text: 'Compreende bem as tecnologias de trabalho atuais e futuras'},
        {id: '26', ability: '13', text: 'Usa a tecnologia de maneira eficaz, para melhorar o desempenho no trabalho'},
        {id: '27', ability: '14', text: 'Assume a responsabilidade pelo próprio desenvolvimento profissional'},
        {id: '28', ability: '14', text: 'Tem planos realistas para atingir suas metas profissionais atuais'},
        {id: '29', ability: '15', text: 'Antevê problemas que poderão comprometer o desempenho'},
        {id: '30', ability: '15', text: 'Busca oportunidades para o crescimento pessoal e profissional'},
        {id: '31', ability: '16', text: 'Sente-se à vontade, mesmo quando o futuro é incerto'},
        {id: '32', ability: '16', text: 'Continua trabalhando com eficácia, mesmo quando lhe faltam informações relevantes'},
        {id: '33', ability: '17', text: 'Sabe lidar bem com recursos limitados'},
        {id: '34', ability: '17', text: 'Ajusta-se bem a um aumento na carga de trabalho'},
        {id: '35', ability: '18', text: 'Consegue assumir outras funções quando necessário'},
        {id: '36', ability: '18', text: 'Consegue mudar seu ponto de vista quando lhe apresentam dados convincentes'},
        {id: '37', ability: '19', text: 'Não se aborrece nem se abala facilmente'},
        {id: '38', ability: '19', text: 'Consegue lidar com altos níveis de estresse'},
        {id: '39', ability: '20', text: 'Dispõe-se a experimentar novas maneiras de se fazer as coisas'},
        {id: '40', ability: '20', text: 'Consegue ter ideias novas, mesmo quando está sob pressão'},
    ],
};

const APEEvaluationSchema = {
    lang: 'pt-BR',
    type: 'ape',
    title: 'APE',
    positive: true,
    schema: {type: 'integer', minimum: 1, maximum: 4},
    competencies: [
        {id: 'discipline', title: 'Disciplina', text: 'Competências Disciplinares'},
        {id: 'initiative', title: 'Iniciativa', text: 'Competências de Iniciativa'},
        {id: 'attendance', title: 'Assiduidade', text: 'Competências de Assiduidade'},
        {id: 'punctuality', title: 'Pontualidade', text: 'Competências de Pontualidade'},
        {id: 'personal_presentation', title: 'Apresentação pessoal', text: 'Competências de Apresentação Pessoal'},
        {id: 'sociability', title: 'Sociabilidade', text: 'Competências de Sociabilidade'},
        {id: 'cooperation', title: 'Cooperação', text: 'Competências de Cooperação'},
        {id: 'dynamism', title: 'Dinamismo', text: 'Competências de Dinamismo'},
        {id: 'leadership', title: 'Liderança', text: 'Competências de Liderança'},
        {id: 'responsibility', title: 'Responsabilidade', text: 'Competências de Responsabilidade'},
        {id: 'efficiency', title: 'Eficiência', text: 'Competências de Eficiência'},
        {id: 'productivity', title: 'Produtividade', text: 'Competências de Produtividade'},
        {id: 'potentiality', title: 'Potencialidade', text: 'Competências de Potencialidade'},
        {id: 'creativity', title: 'Criatividade', text: 'Competências de Criatividade'},
        {id: 'friendliness', title: 'Simpatia', text: 'Competências de Simpatia'},
        {id: 'results_orientation', title: 'Foco no resultado', text: 'Competências de Foco no resultado'},
    ],
    questions: [
        {id: '1', competency: 'discipline', text: 'Obediência às normas da empresa e ordens recebidas.'},
        {id: '2', competency: 'initiative', text: 'Fazer o que tem que ser feito sem esperar ordens.'},
        {id: '3', competency: 'attendance', text: 'Não faltar ao trabalho.'},
        {id: '4', competency: 'punctuality', text: 'Não chegar atrasado e cumprir o horário da empresa.'},
        {id: '5', competency: 'personal_presentation', text: 'Asseio pessoal, roupa e organização do local de trabalho.'},
        {id: '6', competency: 'sociability', text: 'Facilidade para trabalhar em grupo.'},
        {id: '7', competency: 'cooperation', text: 'Contribuição com os outros visando objetivos comuns.'},
        {id: '8', competency: 'dynamism', text: 'Capacidade de agilizar o processo produtivo.'},
        {id: '9', competency: 'leadership', text: 'Capacidade de conduzir os outros a objetivos comuns.'},
        {id: '10', competency: 'responsibility', text: 'Comprometer-se a realizar tudo aquilo que é de sua atribuição.'},
        {id: '11', competency: 'efficiency', text: 'Realização de atribuições dentro dos prazos e critérios de qualidade.'},
        {id: '12', competency: 'productivity', text: 'Qualidade do trabalho apresentado dentro dos critérios de qualidade.'},
        {id: '13', competency: 'potentiality', text: 'Aptidão para exercício de outras atribuições ou funções.'},
        {id: '14', competency: 'creativity', text: 'Capacidade de encontrar soluções diferentes para os mesmos acontecimentos.'},
        {id: '15', competency: 'friendliness', text: 'Habilidade de expressar alegria e felicidade.'},
        {id: '16', competency: 'results_orientation', text: 'Capacidade de olhar para os processos como um todo, focando não na tarefa, mas no resultado.'},
    ],
};

const DecisionMatrixSchema = {
    lang: 'pt-BR',
    type: 'decision-matrix',
    title: 'Matriz de decisão',
    positive: true,
    schema: {type: 'integer', minimum: 0, maximum: 10},
    competencies: [
        {id: 'technical', title: 'Técnica', text: 'Competências Técnicas'},
        {id: 'emotional', title: 'Emocional', text: 'Competências Emocionais'},
    ],

    questions: [
        {id: '1', competency: 'technical', text: 'Prioridade certa no momento certo'},
        {id: '2', competency: 'technical', text: 'Tem compromisso assumido com as metas da organização'},
        {id: '3', competency: 'technical', text: 'Ouve feedbacks alheios e busca ser melhor'},
        {id: '4', competency: 'technical', text: 'Dedica atenção a tudo que faz'},
        {id: '5', competency: 'technical', text: 'Procura trabalhar consistentemente num alto nível na sua função'},
        {id: '6', competency: 'technical', text: 'Cumpre todos os compromissos'},
        {id: '7', competency: 'technical', text: 'Toma decisões apropriadas quando necessário'},
        {id: '8', competency: 'technical', text: 'Informa aos outros quando não terá condições de cumprir uma promessa'},
        {id: '9', competency: 'technical', text: 'Atinge os resultados desejados'},
        {id: '10', competency: 'technical', text: 'Age de maneira positiva ao buscar oportunidades para aprender'},
        {id: '11', competency: 'technical', text: 'Procura exceder as expectativas dos clientes sempre que possível'},
        {id: '12', competency: 'technical', text: 'É habilidoso ao dar e receber feedbacks sobre desempenho'},
        {id: '13', competency: 'technical', text: 'Tem práticas e sistemas eficientes para o seu trabalho individual'},
        {id: '14', competency: 'technical', text: 'Assume a responsabilidade pelo próprio desenvolvimento profissional'},
        {id: '15', competency: 'technical', text: 'Contribui com ideias e sugestões para melhoria na sua função'},
        {id: '16', competency: 'technical', text: 'Compreende bem as tecnologias de trabalho atuais e futuras'},
        {id: '17', competency: 'technical', text: 'Transmite as informações importantes aos outros de maneira eficiente'},
        {id: '18', competency: 'emotional', text: 'Liderança inspiradora: orienta e motiva, com uma visão instigante, conduzindo pessoas a objetivos de ganhos mútuos'},
        {id: '19', competency: 'emotional', text: 'Iniciativa: está sempre pronto para agir e aproveitar oportunidades'},
        {id: '20', competency: 'emotional', text: 'Transparência e Credibilidade: é honesto e íntegro, digno de confiança'},
        {id: '21', competency: 'emotional', text: 'Serviço: reconhece e satisfaz as necessidades dos subordinados e clientes, servindo-os e ajudando-os a melhorar seu desempenho e alcançar seus objetivos'},
        {id: '22', competency: 'emotional', text: 'Trabalho em equipe: conquista a colaboração e o trabalho em equipe, com alto desempenho'},
        {id: '23', competency: 'emotional', text: 'Autoconfiança: ter um sólido senso do próprio valor, capacidades e potencial'},
        {id: '24', competency: 'emotional', text: 'Otimismo: vê o lado bom dos acontecimentos em qualquer situação'},
        {id: '25', competency: 'emotional', text: 'Superação: possui ímpeto para melhorar o desempenho a fim de satisfazer padrões interiores de excelência'},
        {id: '26', competency: 'emotional', text: 'Influência: dispõe da capacidade de persuadir e influenciar pessoas'},
        {id: '27', competency: 'emotional', text: 'Empatia: percebe as emoções alheias, compreende seus pontos de vista e se interessa ativamente pelas preocupações dos outros'},
        {id: '28', competency: 'emotional', text: 'Flexibilidade: tem flexibilidade na adaptação a pessoas com estilo diferente, a situações voláteis ou na maneira de pensar e se comportar em situações antagônicas'},
        {id: '29', competency: 'emotional', text: 'Autocontrole emocional: mantém emoções e impulsos destrutivos sob controle'},
        {id: '30', competency: 'emotional', text: 'Gerenciamento de conflitos: soluciona divergências entre pessoas, levando-as à integração e à aceitação mútua'},
    ],
};

export const EvaluationBaseByType = {
    [EvaluationType.decision_matrix]: DecisionMatrixSchema,
    [EvaluationType.ape]: APEEvaluationSchema,
};

export const APEEvaluation = [
    APEEvaluationSchema,
];

export const DecisionsMatrix = [
    DecisionMatrixSchema,
];

export const MultidirectionalEvaluations = [
    EmotionalInteligenceEvalutionSchema,
    ManagingSkillsEvalutionSchema,
    SellDevelopmentEvalutionSchema,
    WorkEfficacyEvalutionSchema,
    PrideEvalutionSchema,
];

export type APEEvaluationType = typeof APEEvaluationSchema;
export type DecisionMatrixType = typeof DecisionMatrixSchema;
export type MultidirectionalEvaluation = typeof EmotionalInteligenceEvalutionSchema;

export const MultidirectionalEvaluationByType = MultidirectionalEvaluations
    .map(e => ({[e.type]: e}))
    .reduce((obj, field) => Object.assign(obj, field), {});
