resources:
  Resources:
    EvaluationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriEvaluations'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: _employee_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: _employee_id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    EvaluationActionQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'evaluation-action.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    EvaluationActionSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt EvaluationActionQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewEvaluationVersion']

    EvaluationTimelineQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'evaluation-timeline.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    EvaluationTimelineSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt EvaluationTimelineQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewEvaluationVersion']
    EvaluationEmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'evaluation-email.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    EvaluationEmailSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt EvaluationEmailQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewEvaluationVersion']
    CreateEvaluationOnSectorQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'create-evaluation-on-sector.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    CreateEvaluationOnSectorActionSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt CreateEvaluationOnSectorQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['CreateEvaluationOnSector']

    RemoveEvaluationOnSectorQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'remove-evaluation-on-sector.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    RemoveEvaluationOnSectorActionSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt RemoveEvaluationOnSectorQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['RemoveEvaluationOnSector']

    EvaluationMysqlQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'evaluation-mysql.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    EvaluationMysqlActionSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt EvaluationMysqlQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewEvaluationVersion']

    EvaluationExpireQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'evaluation-expire.fifo'
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    EvaluationExpireSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt EvaluationExpireQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['ExpireEvaluation']
