resources:
  Resources:
    PendingActionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriPendingActions'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: _EmployeeDateTypeId
            AttributeType: S
          -
            AttributeName: created_at
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: _EmployeeDateTypeId
            KeyType: RANGE

        GlobalSecondaryIndexes:
          -
            IndexName: 'BarueriPendingActionsByAccountAndDate'
            KeySchema:
              -
                AttributeName: account
                KeyType: HASH
              -
                AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          -
            IndexName: 'BarueriPendingActionsByAccountAndId'
            KeySchema:
              -
                AttributeName: account
                KeyType: HASH
              -
                AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    PendingActionsUpdateQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'pending-actions-update.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    PendingActionsUpdateSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt PendingActionsUpdateQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewPendingActionVersion']

    UserDisabledQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'user-disabled.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    UserDisabledSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt UserDisabledQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewUserVersion']
