resources:
  Resources:
    UnseenItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriUnseenItems'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: _employee_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: _employee_id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    