resources:
  Resources:
    RanksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriRanks'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: _title
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          -
            IndexName: 'BarueriRanksByTitle'
            KeySchema:
              -
                AttributeName: account
                KeyType: HASH
              -
                AttributeName: _title
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    HierarchicalRankQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'hierarchical-rank.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    HierarchicalRankSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt HierarchicalRankQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewRankVersion']