resources:
  Resources:
    FaqTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriFaq'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH