resources:
  Resources:
    FeedbacksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'BarueriFeedbacks'
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: account
            AttributeType: S
          -
            AttributeName: _employee_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: account
            KeyType: HASH
          -
            AttributeName: _employee_id
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    FeedbackActionQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'feedback-action.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    FeedbackActionSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt FeedbackActionQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewFeedbackVersion']

    FeedbackTimelineQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'feedback-timeline.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    FeedbackTimelineSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt FeedbackTimelineQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewFeedbackVersion']

    FeedbackMysqlQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'feedback-mysql.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    FeedbackMysqlSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt FeedbackMysqlQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewFeedbackVersion']

    FeedbackEmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        ContentBasedDeduplication: true
        FifoQueue: true
        QueueName: 'feedback-email.fifo'
        DelaySeconds: 0
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLettersQueue.Arn
          maxReceiveCount: 5
        VisibilityTimeout: 180
    FeedbackEmailSub:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        Endpoint: !GetAtt FeedbackEmailQueue.Arn
        TopicArn: !Ref MainTopic
        FilterPolicy:
          Type: ['NewFeedbackVersion']
